name: New Issue Opened
on:
    issues:
        types: [opened, closed]
jobs:
    new-issue-opened-job:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub Context
              run: echo "${{ toJSON(github) }}"
