name: Manually Triggered Workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: |
                  echo "Hello, world!"
                  echo "second print"
            - name: Print goodbye
              run: echo "Done, bye!"
